# Project

## Project introduction


## Minimal Requirements


## More Ideas


## Curriculum

In the next months we will have 4+1 meetups. The following is intended to give you some direction on what we think would be a good working-pace for your project. We won't spoil much here, but instead give some hints and make you aware of problems you may encounter.  

You don't need to watch the whole course but if you have the time it can be really helpful. We tried to cut some of the less important stuff (for this project) out of the course. We will also tell you how much time you need to plan for watching the sections. But remember that you might need more time.


### 09.11.2022 - Web-Dev Coding Introduction {-}

#### Udemy Course {-}

You don't need to watch any sections for the Introduction Meetup. We will cover the sections 3, 4 and 5 from the Udemy Course together in class. We will go over the basics of Web Development and HTML. Moreover you will build your first website. Please remember to bring your own laptop!

### 23.11.2022 - 1. Coding Meetup {-}

#### Udemy Course {-}


#### Action {-}


### 14.12.2022 - 2. Coding Meetup {-}

#### Udemy Course {-}


#### Action {-}


### 11.01.2023 - 3. Coding Meetup {-}

#### Udemy Course {-}


#### Action {-}


### 01.02.2023 - 4. Coding Meetup {-}

#### Udemy Course {-}



#### Action {-}

